import type { DashboardSecondaryPerformanceGroup } from './dashboardTypes';

export const dashboardSecondaryPerformanceGroups: DashboardSecondaryPerformanceGroup[] = [
  {
    tone: 'peach',
    footerLabel: 'WEEK TOTAL',
    summary: {
      members: 4,
      avgPoints: 44,
    },
    members: [
      {
        rank: 1,
        name: 'Sachin Sir',
        meetingBreakupKey: 'SACHIN_SIR',
        yesterdayMeetings: 6,
        yesterdayClients: 2,
        todayMeetings: 3,
        todayClients: 1,
        teamMeetings: 18,
        selfMeetings: 11,
        clients: { actual: 9, documentsReceived: 5 },
        sachinSir: 62,
        points: 98,
      },
      {
        rank: 2,
        name: 'Alok',
        meetingBreakupKey: 'ALOK',
        yesterdayMeetings: 5,
        yesterdayClients: 1,
        todayMeetings: 2,
        todayClients: 1,
        teamMeetings: 16,
        selfMeetings: 9,
        clients: { actual: 7, documentsReceived: 4 },
        sachinSir: 58,
        points: 90,
      },
      {
        rank: 3,
        name: 'Ashutosh',
        meetingBreakupKey: 'ASHUTOSH',
        yesterdayMeetings: 4,
        yesterdayClients: 1,
        todayMeetings: 2,
        todayClients: 0,
        teamMeetings: 14,
        selfMeetings: 8,
        clients: { actual: 6, documentsReceived: 3 },
        sachinSir: 55,
        points: 84,
      },
      {
        rank: 4,
        name: 'Harsh',
        meetingBreakupKey: 'HARSH',
        yesterdayMeetings: 3,
        yesterdayClients: 0,
        todayMeetings: 1,
        todayClients: 0,
        teamMeetings: 12,
        selfMeetings: 7,
        clients: { actual: 5, documentsReceived: 2 },
        sachinSir: 51,
        points: 76,
      },
    ],
  },
] satisfies DashboardSecondaryPerformanceGroup[];
