import type { DashboardPerformanceRow, DashboardTableColumn } from './dashboardTypes';

export const dashboardPerformanceRows: Record<string, DashboardPerformanceRow[]> = {
  'Current Week': [
    {
      employee: 'Rahul Sharma',
      meetings: { yesterday: 4, today: 2 },
      clients: { yesterday: 2, today: 1 },
      leads: { target: 30, achieved: 22 },
      meetingsWeek: { target: 18, achieved: 14 },
      clientsWeek: { target: 10, achieved: 7 },
      documentsReceived: 11,
      points: 240,
    },
    {
      employee: 'Aman Singh',
      meetings: { yesterday: 5, today: 3 },
      clients: { yesterday: 1, today: 2 },
      leads: { target: 32, achieved: 26 },
      meetingsWeek: { target: 20, achieved: 16 },
      clientsWeek: { target: 9, achieved: 6 },
      documentsReceived: 9,
      points: 210,
    },
    {
      employee: 'Neha Kumari',
      meetings: { yesterday: 3, today: 2 },
      clients: { yesterday: 1, today: 0 },
      leads: { target: 28, achieved: 20 },
      meetingsWeek: { target: 15, achieved: 11 },
      clientsWeek: { target: 8, achieved: 5 },
      documentsReceived: 8,
      points: 185,
    },
    {
      employee: 'Karan Verma',
      meetings: { yesterday: 2, today: 1 },
      clients: { yesterday: 0, today: 1 },
      leads: { target: 25, achieved: 18 },
      meetingsWeek: { target: 12, achieved: 10 },
      clientsWeek: { target: 6, achieved: 4 },
      documentsReceived: 6,
      points: 160,
    },
    {
      employee: 'Rohit Gupta',
      meetings: { yesterday: 2, today: 1 },
      clients: { yesterday: 1, today: 1 },
      leads: { target: 24, achieved: 15 },
      meetingsWeek: { target: 10, achieved: 8 },
      clientsWeek: { target: 5, achieved: 3 },
      documentsReceived: 5,
      points: 140,
    },
    {
      employee: 'Priya Mehta',
      meetings: { yesterday: 4, today: 2 },
      clients: { yesterday: 1, today: 1 },
      leads: { target: 26, achieved: 19 },
      meetingsWeek: { target: 16, achieved: 12 },
      clientsWeek: { target: 7, achieved: 5 },
      documentsReceived: 7,
      points: 135,
    },
    {
      employee: 'Suresh Patel',
      meetings: { yesterday: 1, today: 1 },
      clients: { yesterday: 0, today: 0 },
      leads: { target: 20, achieved: 12 },
      meetingsWeek: { target: 8, achieved: 6 },
      clientsWeek: { target: 3, achieved: 2 },
      documentsReceived: 3,
      points: 110,
    },
    {
      employee: 'Sneha Reddy',
      meetings: { yesterday: 2, today: 1 },
      clients: { yesterday: 1, today: 0 },
      leads: { target: 18, achieved: 9 },
      meetingsWeek: { target: 6, achieved: 5 },
      clientsWeek: { target: 3, achieved: 2 },
      documentsReceived: 3,
      points: 95,
    },
  ],
  Today: [
    {
      employee: 'Rahul Sharma',
      meetings: { yesterday: 4, today: 2 },
      clients: { yesterday: 2, today: 1 },
      leads: { target: 30, achieved: 22 },
      meetingsWeek: { target: 18, achieved: 14 },
      clientsWeek: { target: 10, achieved: 7 },
      documentsReceived: 11,
      points: 52,
    },
    {
      employee: 'Aman Singh',
      meetings: { yesterday: 5, today: 3 },
      clients: { yesterday: 1, today: 2 },
      leads: { target: 32, achieved: 26 },
      meetingsWeek: { target: 20, achieved: 16 },
      clientsWeek: { target: 9, achieved: 6 },
      documentsReceived: 9,
      points: 48,
    },
    {
      employee: 'Neha Kumari',
      meetings: { yesterday: 3, today: 2 },
      clients: { yesterday: 1, today: 0 },
      leads: { target: 28, achieved: 20 },
      meetingsWeek: { target: 15, achieved: 11 },
      clientsWeek: { target: 8, achieved: 5 },
      documentsReceived: 8,
      points: 44,
    },
    {
      employee: 'Karan Verma',
      meetings: { yesterday: 2, today: 1 },
      clients: { yesterday: 0, today: 1 },
      leads: { target: 25, achieved: 18 },
      meetingsWeek: { target: 12, achieved: 10 },
      clientsWeek: { target: 6, achieved: 4 },
      documentsReceived: 6,
      points: 41,
    },
  ],
  Yesterday: [
    {
      employee: 'Rahul Sharma',
      meetings: { yesterday: 4, today: 2 },
      clients: { yesterday: 2, today: 1 },
      leads: { target: 30, achieved: 22 },
      meetingsWeek: { target: 18, achieved: 14 },
      clientsWeek: { target: 10, achieved: 7 },
      documentsReceived: 11,
      points: 64,
    },
    {
      employee: 'Aman Singh',
      meetings: { yesterday: 5, today: 3 },
      clients: { yesterday: 1, today: 2 },
      leads: { target: 32, achieved: 26 },
      meetingsWeek: { target: 20, achieved: 16 },
      clientsWeek: { target: 9, achieved: 6 },
      documentsReceived: 9,
      points: 57,
    },
    {
      employee: 'Neha Kumari',
      meetings: { yesterday: 3, today: 2 },
      clients: { yesterday: 1, today: 0 },
      leads: { target: 28, achieved: 20 },
      meetingsWeek: { target: 15, achieved: 11 },
      clientsWeek: { target: 8, achieved: 5 },
      documentsReceived: 8,
      points: 51,
    },
    {
      employee: 'Karan Verma',
      meetings: { yesterday: 2, today: 1 },
      clients: { yesterday: 0, today: 1 },
      leads: { target: 25, achieved: 18 },
      meetingsWeek: { target: 12, achieved: 10 },
      clientsWeek: { target: 6, achieved: 4 },
      documentsReceived: 6,
      points: 46,
    },
  ],
};

export const dashboardPerformanceColumns: DashboardTableColumn[] = [
  { key: 'employee', label: 'Name', width: 132, align: 'left', valueType: 'text' },
  { key: 'yesterdayMeetings', label: 'Yes. Meeting', width: 108, valueType: 'number' },
  { key: 'todayMeetings', label: 'Tod. Meeting', width: 108, valueType: 'number' },
  { key: 'yesterdayClients', label: 'Yes. Client', width: 108, valueType: 'number' },
  { key: 'todayClients', label: 'Tod. Client', width: 108, valueType: 'number' },
  { key: 'leadTarget', label: 'Leads Tar.', width: 84, valueType: 'number' },
  { key: 'leadAchieved', label: 'Leads Ach.', width: 84, valueType: 'number' },
  { key: 'meetingTarget', label: 'Meeting Tar.', width: 84, valueType: 'number' },
  { key: 'meetingAchieved', label: 'Meeting Ach.', width: 84, valueType: 'number' },
  { key: 'clientTarget', label: 'Client Tar.', width: 84, valueType: 'number' },
  { key: 'clientAchieved', label: 'Client Ach.', width: 84, valueType: 'number' },
  { key: 'docs', label: 'Docs', width: 84, valueType: 'number' },
  { key: 'points', label: 'Points', width: 72, valueType: 'number' },
];
