import type { DashboardTeamPerformanceGroup } from './dashboardTypes';

export const dashboardTeamPerformanceGroups: DashboardTeamPerformanceGroup[] = [
  {
    teamName: 'Ashutosh',
    tone: 'peach',
    summary: {
      members: 4,
      avgPoints: 47.5,
      avgMeetings: 16,
      rptClients: 1,
    },
    members: [
      {
        rank: 1,
        name: 'Umakant',
        yesterdayMeetings: 7,
        yesterdayClients: 1,
        todayMeetings: 0,
        todayClients: 0,
        leads: { achieved: 4, target: 40, pendingPercent: 50 },
        meetings: { achieved: 16, target: 12, pendingPercent: 0 },
        clients: { achieved: 1, target: 2, pendingPercent: 50 },
        documentsReceived: 0,
        points: 60,
      },
      {
        rank: 2,
        name: 'Saket',
        yesterdayMeetings: 11,
        yesterdayClients: 0,
        todayMeetings: 0,
        todayClients: 0,
        leads: { achieved: 5, target: 40, pendingPercent: 37 },
        meetings: { achieved: 25, target: 12, pendingPercent: 0 },
        clients: { achieved: 0, target: 2, pendingPercent: 100 },
        documentsReceived: 0,
        points: 60,
      },
      {
        rank: 3,
        name: 'Sunny',
        yesterdayMeetings: 9,
        yesterdayClients: 0,
        todayMeetings: 0,
        todayClients: 0,
        leads: { achieved: 5, target: 40, pendingPercent: 37 },
        meetings: { achieved: 23, target: 12, pendingPercent: 0 },
        clients: { achieved: 0, target: 2, pendingPercent: 100 },
        documentsReceived: 0,
        points: 56,
      },
      {
        rank: 4,
        name: 'Satyam',
        yesterdayMeetings: 6,
        yesterdayClients: 0,
        todayMeetings: 0,
        todayClients: 0,
        leads: { achieved: 7, target: 40, pendingPercent: 12 },
        meetings: { achieved: 0, target: 12, pendingPercent: 100 },
        clients: { achieved: 0, target: 2, pendingPercent: 100 },
        documentsReceived: 0,
        points: 14,
      },
    ],
  },
  {
    teamName: 'Harsh',
    tone: 'blue',
    summary: {
      members: 5,
      avgPoints: 45.2,
      avgMeetings: 17.6,
      rptClients: 0,
    },
    members: [
      {
        rank: 1,
        name: 'Rajat',
        yesterdayMeetings: 10,
        yesterdayClients: 0,
        todayMeetings: 0,
        todayClients: 0,
        leads: { achieved: 9, target: 40, pendingPercent: 0 },
        meetings: { achieved: 19, target: 12, pendingPercent: 0 },
        clients: { achieved: 0, target: 2, pendingPercent: 100 },
        documentsReceived: 0,
        points: 60,
      },
      {
        rank: 2,
        name: 'Atul',
        yesterdayMeetings: 9,
        yesterdayClients: 0,
        todayMeetings: 0,
        todayClients: 0,
        leads: { achieved: 1, target: 40, pendingPercent: 87 },
        meetings: { achieved: 23, target: 12, pendingPercent: 0 },
        clients: { achieved: 0, target: 2, pendingPercent: 100 },
        documentsReceived: 0,
        points: 48,
      },
      {
        rank: 3,
        name: 'Rakesh',
        yesterdayMeetings: 5,
        yesterdayClients: 0,
        todayMeetings: 0,
        todayClients: 0,
        leads: { achieved: 0, target: 40, pendingPercent: 100 },
        meetings: { achieved: 20, target: 12, pendingPercent: 0 },
        clients: { achieved: 0, target: 2, pendingPercent: 100 },
        documentsReceived: 0,
        points: 40,
      },
      {
        rank: 4,
        name: 'Garv',
        yesterdayMeetings: 8,
        yesterdayClients: 0,
        todayMeetings: 0,
        todayClients: 0,
        leads: { achieved: 10, target: 40, pendingPercent: 0 },
        meetings: { achieved: 10, target: 12, pendingPercent: 17 },
        clients: { achieved: 0, target: 2, pendingPercent: 100 },
        documentsReceived: 0,
        points: 40,
      },
      {
        rank: 5,
        name: 'Ameet',
        yesterdayMeetings: 8,
        yesterdayClients: 0,
        todayMeetings: 0,
        todayClients: 0,
        leads: { achieved: 3, target: 40, pendingPercent: 62 },
        meetings: { achieved: 16, target: 12, pendingPercent: 0 },
        clients: { achieved: 0, target: 2, pendingPercent: 100 },
        documentsReceived: 0,
        points: 38,
      },
    ],
  },
  {
    teamName: 'Alok',
    tone: 'green',
    summary: {
      members: 5,
      avgPoints: 40.8,
      avgMeetings: 11.4,
      rptClients: 0,
    },
    members: [
      {
        rank: 1,
        name: 'Tejprakash',
        yesterdayMeetings: 11,
        yesterdayClients: 0,
        todayMeetings: 0,
        todayClients: 0,
        leads: { achieved: 10, target: 40, pendingPercent: 0 },
        meetings: { achieved: 18, target: 12, pendingPercent: 0 },
        clients: { achieved: 0, target: 2, pendingPercent: 100 },
        documentsReceived: 0,
        points: 56,
      },
      {
        rank: 2,
        name: 'Harsh.P',
        yesterdayMeetings: 9,
        yesterdayClients: 0,
        todayMeetings: 0,
        todayClients: 0,
        leads: { achieved: 12, target: 40, pendingPercent: 0 },
        meetings: { achieved: 14, target: 12, pendingPercent: 0 },
        clients: { achieved: 0, target: 2, pendingPercent: 100 },
        documentsReceived: 0,
        points: 52,
      },
      {
        rank: 3,
        name: 'Abhay',
        yesterdayMeetings: 12,
        yesterdayClients: 0,
        todayMeetings: 0,
        todayClients: 0,
        leads: { achieved: 10, target: 40, pendingPercent: 0 },
        meetings: { achieved: 12, target: 12, pendingPercent: 0 },
        clients: { achieved: 0, target: 2, pendingPercent: 100 },
        documentsReceived: 0,
        points: 44,
      },
      {
        rank: 4,
        name: 'Amit',
        yesterdayMeetings: 0,
        yesterdayClients: 0,
        todayMeetings: 0,
        todayClients: 0,
        leads: { achieved: 9, target: 40, pendingPercent: 0 },
        meetings: { achieved: 7, target: 12, pendingPercent: 42 },
        clients: { achieved: 0, target: 2, pendingPercent: 100 },
        documentsReceived: 0,
        points: 32,
      },
      {
        rank: 5,
        name: 'Abhijeet',
        yesterdayMeetings: 10,
        yesterdayClients: 0,
        todayMeetings: 0,
        todayClients: 0,
        leads: { achieved: 4, target: 40, pendingPercent: 50 },
        meetings: { achieved: 6, target: 12, pendingPercent: 50 },
        clients: { achieved: 0, target: 2, pendingPercent: 100 },
        documentsReceived: 0,
        points: 20,
      },
    ],
  },
];
